project:
  type: website
  output-dir: docs

website:
  title: "Digital behavioral data"
  description: "Homepage of the course 'Digital behavioral data‘ at Friedrich-Alexander-Universtität (FAU) Erlangen-Nürnberg"
  favicon: "img/logo_fau_red.svg"
  page-navigation: true
  open-graph: true
  reader-mode: false

  # cookie-consent:
  #   type: express
  #   style: headline
  #   palette: light

  repo-url: https://github.com/chrdrn/dbd_2025
  repo-actions: [edit, issue]
    
  sidebar:
    logo: "img/dbd_hex.png"
    align: center
    tools: 
    - icon: globe
      href: https://www.kommunikationswissenschaft.rw.fau.de/lehre/master/digital-behavioral-data/
    - icon: bookmark
      href: https://www.studon.fau.de/studon/go/crs/6572953
      text: StudOn course
    - icon: github
      href: https://github.com/chrdrn/dbd_2025
      text: Course repository
    # - icon: chat-dots
    #   href: https://fau-dbd.zulipchat.com/
    #   text: DBD Zulip
    # - icon: cloud-arrow-up
    #   href: https://mybinder.org/v2/gh/faucommsci/dbd_binder/HEAD?urlpath=rstudio
    #   text: DBD Binder
    # - icon: server
    #   href: http://10.204.20.178/
    #   text: DBD 4CAT-Server
    
    style: "floating"
    search: true
    collapse-level: 1
    contents: 
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-assignments.qmd
            text: Assignments
          - href: index.qmd
            text: Schedule
          - href: course-team.qmd
            text: Teaching team

    #   - section: "Data collection"
    #     contents:
    #       - href: data_collection/01_01-data_collection-presidential_debate.qmd
    #       - href: data_collection/01_02-data_collection-vice_presidential_debate.qmd
    #       # - href: data_collection/01_03-data_collection-twitch_streamer_stats.qmd
    #       - href: data_collection/01_11-data_processing-chats.qmd
    #       - href: data_collection/01_12-data_processing-transcripts.qmd
    #       - href: data_collection/01_21-corpora_chats-creation.qmd
    #       - href: data_collection/01_22-corpora_transcripts-creation.qmd
    #       - href: data_collection/02_01-qc-chat-emotes.qmd
    #       - href: data_collection/02_02-qc-chat-badges.qmd

    # #   - section: "Sessions"
    #     contents:
    #       - href: sessions/session-01.qmd
    #         text: "Session 01"
    #       - href: sessions/session-02.qmd
    #         text: "Session 02"
    #       - href: sessions/session-03.qmd
    #         text: "Session 03"
    #       - href: sessions/session-04.qmd
    #         text: "Session 04"
    #       - href: sessions/session-06.qmd
    #         text: "Session 06"
    #       - href: sessions/session-07.qmd
    #         text: "Session 07"
    #       - href: sessions/session-08.qmd
    #         text: "Session 08"
    #       - href: sessions/session-09.qmd
    #         text: "Session 09"
    #       - href: sessions/session-10.qmd
    #         text: "Session 10"

    #   - section: "Exercises"
    #     contents:
    #       - href: exercise/exercise-03.qmd
    #         text: "Exercise 03"
    #       - href: exercise/exercise-09_solution.qmd
    #         text: "Exercise 09"
    #       - href: exercise/exercise-10.qmd
    #         text: "Exercise 10"

      - section: "Working with R"
        contents:
          - href: computing/computing-instructions_R.qmd
            text: R Video Tutorials
          - href: computing/computing-textbooks.qmd
            text: R Textbooks
          - href: computing/computing-cheatsheets.qmd
            text: R Cheatsheets
          - href: computing/computing-useful_links.qmd
            text: Useful R sources
            
  page-footer: 
   left: "Copyright 2024, Christoph Adrian"
   right: "This page is built with ☕ & [Quarto](https://quarto.org/)."

format:
  html:
    theme:
      light: [journal, theme.scss]
      dark: [journal, theme-dark.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto